-- 建立数据库
CREATE DATABASE `im` DEFAULT charset=utf8;

-- 测试表建立
DROP TABLE IF EXISTS `test`;
CREATE TABLE IF NOT EXISTS `test`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` VARCHAR(128) NOT NULL COMMENT '测试',
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updata_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=未激活,1=激活',
  PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='测试表管理';

-- 用户表建立
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `acid` VARCHAR(32) NOT NULL COMMENT 'IM账号',
  `password` VARCHAR(32) NOT NULL COMMENT '密码',
  `tel` BIGINT(11) NOT NULL COMMENT '用户手机',
  `email` VARCHAR(32) DEFAULT NULL COMMENT '用户邮箱',
  `nick` VARCHAR(32) DEFAULT NULL COMMENT '昵称',
  `sex` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=未知,1=男,2=女',
  `pic` VARCHAR(256) DEFAULT NULL COMMENT '头像',
  `sign` VARCHAR(256) DEFAULT NULL COMMENT '个性签名',
  `birthday` TIMESTAMP DEFAULT NULL COMMENT '生日',
  `usertype` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态(单选):0=普通,1=管理员',
  `reg_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=未激活,1=激活',
  PRIMARY KEY(`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `tel` (`tel`),
  UNIQUE KEY `nick` (`nick`),
  UNIQUE KEY `acid` (`acid`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户管理';